/******************************************************************************
 * This file was generated by langium-visitor.
 * DO NOT EDIT MANUALLY!
 ******************************************************************************/

import * as ASTInterfaces from '../language/generated/ast.js';
import { LangiumCoreServices, Reference, ValidationAcceptor, ValidationChecks } from 'langium';

/**
 * This interface is used to define the visitor methods for the HelloWorld language.
 */
export interface HelloWorldVisitor {
    visitGreeting(node : Greeting) : any;
    visitModel(node : Model) : any;
    visitPerson(node : Person) : any;
}

/**
 * This abstract class is used to implement a validation visitor for the HelloWorld language.
 * It uses the Langium validator service under the hood and exposes its `accept` method through the `validationAccept` property.
 * This `validationAccept` property is reassigned each time the `visitRoot` method is called, so when Langium called the different validation checks.
 */
export abstract class HelloWorldValidationVisitor {

    protected validationAccept: ValidationAcceptor = () => {};

    visitRoot(node: Model, accept: ValidationAcceptor) {
        this.validationAccept = accept;
        node.accept(this);
    }
    
    abstract visitGreeting(node : Greeting) : any;
    abstract visitModel(node : Model) : any;
    abstract visitPerson(node : Person) : any;
}


/**
 * This function is used to register a validation visitor for the HelloWorld language.
 * It will register the `visitRoot` method as a validation check for the Model type.
 * @param visitor - The visitor to register.
 * @param services - The Langium services.
 */
export function registerVisitorAsValidator<T extends HelloWorldValidationVisitor>(visitor: T, services: LangiumCoreServices) {
    const registry = services.validation.ValidationRegistry;
    const checks: ValidationChecks<ASTInterfaces.HelloWorldAstType> = {
        Model: (node, accept) => {
            visitor.visitRoot(node as Model, accept);
        }
    };
    registry.register(checks, visitor);
}


/* Each concrete interfaces in the `ast.js` file have an equivalent generated class with the same properties but also with an `accept` method.
 * While the generated accept-weaver allows us to dynamically add the `accept` function to Langium's types, these classes allow it to exist statically, so we can take advantage of TypeScript's typing.
 * Nevertheless, the two are strictly equivalent, and conversion from one to the other is made possible thanks to duck-typing.
 */

export class Greeting implements ASTInterfaces.Greeting {
    
    constructor(public $type: 'Greeting', public $container: Model, public person: Reference<Person>) {
    }
    
     accept(visitor: HelloWorldVisitor) : any {
        return visitor.visitGreeting(this);
    }
}

export class Model implements ASTInterfaces.Model {
    
    constructor(public $type: 'Model', public persons: Person[], public greetings: Greeting[]) {
    }
    
     accept(visitor: HelloWorldVisitor) : any {
        return visitor.visitModel(this);
    }
}

export class Person implements ASTInterfaces.Person {
    
    constructor(public $type: 'Person', public $container: Model, public name: string) {
    }
    
     accept(visitor: HelloWorldVisitor) : any {
        return visitor.visitPerson(this);
    }
}
